class Commands:
    LEECH = "leech@kratosleechbot"
    PURGE = "purge@kratosleechbot"
    PAUSEALL = "pauseall@kratosleechbot"
    RESUMEALL = "resumeall@kratosleechbot"
    STATUS = "status@kratosleechbot"
    SETTINGS = "settings@kratosleechbot"
    EXEC = "exec@kratosleechbot"
    UPLOAD = "upload@kratosleechbot"
    YTDL = "ytdl@kratosleechbot"
    PYTDL = "pytdl@kratosleechbot"
    ABOUT = "about@kratosleechbot"
    GETLOGS = "getlogs@kratosleechbot"
    SERVER = "server@kratosleechbot"
    USERSETTINGS = "usetting@kratosleechbot"
    INSTADL = "instadl@kratosleechbot"
