class Commands:
    LEECH = "leech@torleechpro_bot"
    PURGE = "purge@torleechpro_bot"
    PAUSEALL = "pauseall@torleechpro_bot"
    RESUMEALL = "resumeall@torleechpro_bot"
    STATUS = "status@torleechpro_bot"
    SETTINGS = "settings"
    EXEC = "exec"
    UPLOAD = "upload@torleechpro_bot"
    YTDL = "ytdl@torleechpro_bot"
    PYTDL = "pytdl@torleechpro_bot"
    ABOUT = "about"
    GETLOGS = "getlogs"
    SERVER = "server@torleechpro_bot"
    USERSETTINGS = "usetting@torleechpro_bot"
    INSTADL = "instadl@torleechpro_bot"
